In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [4]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [8]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [13]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [17]:
np.random.randint(50,101,size=(50, 5))

array([[ 55,  64,  71,  82,  86],
       [ 86,  52,  98,  91, 100],
       [ 52,  72,  84,  91,  54],
       [ 59,  93,  82,  63,  69],
       [ 56,  91,  86,  98,  52],
       [ 98,  92,  73,  72,  70],
       [ 54,  93,  71,  95,  74],
       [ 86,  68,  51,  50,  91],
       [ 60,  62,  96,  95,  68],
       [ 75,  72,  75,  82,  64],
       [ 83,  76,  59,  69,  70],
       [ 95,  99,  69,  77,  98],
       [ 63,  51,  58,  81,  63],
       [ 88,  79,  55,  63,  62],
       [ 66,  63,  78,  71,  68],
       [ 85,  97,  57,  80,  73],
       [ 69,  99,  74,  94,  67],
       [ 90,  63,  72,  95,  71],
       [ 79,  70,  54,  53,  56],
       [ 77,  56,  99,  68,  94],
       [ 99,  83,  93,  69,  79],
       [ 95,  92,  99,  65,  66],
       [ 55,  91,  98,  57,  58],
       [ 53,  56,  54,  94,  87],
       [ 90,  69,  57,  99,  94],
       [ 50,  71,  72,  95,  84],
       [ 68,  73,  64,  93,  86],
       [ 95,  78,  54,  77,  51],
       [ 81,  73,  96,  52,  58],
       [ 50,  